# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-17 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=200)),
                ('artist_wordcloud', models.ImageField(upload_to='wordclouds')),
            ],
        ),
        migrations.DeleteModel(
            name='Aritst',
        ),
    ]
