# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-17 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0002_auto_20171017_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lyrics', models.CharField(max_length=10000)),
            ],
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='artist_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='artist_wordcloud',
        ),
        migrations.AddField(
            model_name='artist',
            name='lyrics',
            field=models.CharField(default='hello', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyrics.Artist'),
        ),
    ]
